name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint yapf

      - name: Run Lint
        run: |
          pylint src/
          yapf -dr src/

      - name: Run Tests
        run: |
          pytest tests/

      - name: GitHub CodeQL Init
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/YOUR_PROJECT/my-app:${{ github.sha }} .

      - name: Scan Container with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: gcr.io/YOUR_PROJECT/my-app:${{ github.sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Push Image to Google Artifact Registry
        run: |
          gcloud auth configure-docker
          docker push gcr.io/YOUR_PROJECT/my-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml