apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: europe-west1-docker.pkg.dev/devsecops-460913/devsecops-repo/my-app:latest
          ports:
            - containerPort: 5000