name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint yapf bandit

      - name: Run Lint
        run: |
          pylint src/
          yapf -r -i src/

      - name: Run Tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/

      - name: SAST (Bandit)
        run: bandit -r src/

      - name: GitHub CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/devsecops-460913/devsecops-repo/my-app:${{ github.sha }} .

      - name: Scan Container with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: europe-west1-docker.pkg.dev/devsecops-460913/devsecops-repo/my-app:${{ github.sha }}

      - name: Push Image to Google Artifact Registry
        run: docker push europe-west1-docker.pkg.dev/devsecops-460913/devsecops-repo/my-app:${{ github.sha }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials devsecops-cluster \
            --zone europe-west1-b --project devsecops-460913

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml